### PR TITLE
New voting

### LINKED ISSUE #92: Voting and Staking
Consider how a voting library could be built for DAO.sol.

The idea is that there are several actions that can be voted. The actions are known at coding time (for example, investing in a new venture, distributing dividends and raising funds).

Voting is the same for all actions. There is a staking token and each token is one vote. Each token cannot be used for more than one voting simultaneously.

I would like the logic to be reused between voting actions, only changing the resulting action if the vote is successful.

We might have to mess with function signatures and things like that, no idea really.

### PR DESCRIPTION
**Pull request by uivlis**
The end is to have the `DAO` inherit from `Society`. This is a petty draft, lots of things need to be done, but just to show you the vision I managed to compile the whole thing.

Please, don't wonder what the ?!$% is this...

### CODE REVIEW

**Comment by albertocuestacanada** [comment]
Sooo, @uivlis, very cool that you went on to code a national organization in solidity, but what I wanted was just some kind of contract or library that could be reused to implement voting in other contracts.

Please tell me, what the ?!$% do I do with this?

**Comment by uivlis** [comment]
Right, so I know it's not easy to see it now, but I need one or two days to finish this and the elegancy of the solution will come as a shock: `Society.sol` isn't merely a nation; it's a... society, or any organization, for that matter (including corporations, VC funds, `DAO`'s, Issuances and, yes, nations. What it does is that it provides any contract with highly customizable voting rules and functions in order to enact certain `Bill`s (a bill is nothing else but a call to a certain function of a certain contract). The society will have three branches (plus the members which are part of none of these branches, but are part of Society): the legislative, whose members propose bills, the judiciary, whose members ratify them, and the executive, whose memebrs enact them. Think of it in the case of the DAO: some people decide where to invest, other people ratify (or vote on) the decision, and, finally, someone is responsible to investing and collecting the dividends. Additionally, each branch has its own terms for admission and resignation (including society (so, the DAO itself)) and terms for deciding vote majorities (a detailed description of these possible terms is found in `Terms.sol`. On top of that, there is also a Bank (which is a `VentureEth` and `UniswapFactory`). This bank will act like a Treasury and will be able to issue to investors, return dividends into and exchange tokens to and from the token of the society. In our example, the `DAO` will inherit from `Society`.

**Comment by uivlis** [comment]
Let me give you an example: suppose you wanted the simplest, most direct and efficient society, where everybody cand vote on anything censitarilly, equally and universally, with a price of 1 token per vote ( that is, canVote[member] = true for any member, max(votes[member]) = 1,  price(vote) = 1 token), and everybody can do anything (propose, judge, execute etc.) (that, incidentally, is, I believe, what you asked from me). That is possible with `Society.sol`. The trick lies in choosing the right terms for the constitutions of each branch, which cannot be altered afterwards.

**Comment by uivlis** [comment]
But, remember, this is just a skeleton, things aren't fully clear and decided for me, neither. I may be taking an unnecessary risk by generalizing the task too much... or I may not: imagine the possibilities! (and the articles...). 

The idea came to me after trying to abstract a potential `Voting` contract, it seems that voting (or the lack thereof) is the essential characteristic of a society, and it's inseparable from the members of such a society. Then, it all came to me in the form you see.

Now, does this sound interesting and pursuable, or am I wasting time?

**Comment by albertocuestacanada** [comment]
The more general is a solution, the more complex it will be.

I like the current `DAO.sol` because of its simplicity. It serves my purposes of explaining DAOs well.

It seems to me that the essence of a DAO is that the rules are coded in a smart contract and decisions are taken by voting. Many DAOs are possible within this concept, from the simple to the complex.

My purpose of a voting contract or library is to promote code reuse. The voting mechanism is probably always the same with a few parameters (voting rights, quorum, decisive majority and proposal). In a DAO that can vote on a few different proposal types I'm keen on making it simple.

I'm not going to ask you to stop development on `Society`, but I think that given the complexity and size it should be on a separate repo. You should try to reuse code from `hq20-contracts`, and maybe abstract some reusable components (voting?).

**Comment by uivlis** [comment]
Alright, l'll start anew.

**Comment by albertocuestacanada** [comment]
I'm happy for you to continue with this after `Voting`. I do think it impressive that you thought of all this. If anything I would like you to be aware of the complexity of what you are doing, and whether you are trying to build [Aragon](https://aragon.org/) by yourself.

**Pull request closed without merging**
