### PR TITLE
DAO related changes for Issuance

### PR DESCRIPTION
**Pull request by uivlis**
Hmm, some tests for `IssuanceEth` fail, although I wonder why, all I can see is an `out of gas` error. Tried increasing the tx gas, the block gas, I must ask your help @albertocuestacanada.

### CODE REVIEW

**Comment by albertocuestacanada** [comment]
I doubt that this is a gas related issue, @uivlis. It is more likely that there is a problem with the contract linking. For example if you cast an `address` into a contract and try to execute a function that doesn't exist you will get an `out of gas`.

**Comment by uivlis** [comment]
@albertocuestacanada you are right, my insight is that the fallback function of `IssuanceEth` is not found in the `IssuanceEthInstance` contract interface. @obernardovieira is that correct?

**Comment by obernardovieira** [comment]
It really "runs out of gas". That fallback function is way too complex and expensive...

Just a paragraph from https://programtheblockchain.com/posts/2017/12/16/be-careful-when-using-the-solidity-fallback-function/
```It is possible to put code in the body of this function, but it’s generally considered bad practice to put anything beyond very short, simple logic. The reason is important and unique to smart contracts: you don’t want this function to fail because it runs out of gas. This is a concern because many account-to-account direct transfers of ether are given a default amount of gas, which is actually quite small. To avoid running out of gas, it’s important that the function’s code use less gas than this default amount. As a rule of thumb, you will have just enough gas to log an event, but not enough to write data to storage.```

By changing the fallback function to 
```solidity
function () external payable {
    require(
        currentState == "OPEN"
    );
    require(
        msg.value.mod(issuePrice) == 0
    );

    investors[msg.sender] = true;

    investments[msg.sender] = investments[msg.sender].add(msg.value);

    amountRaised = amountRaised.add(msg.value);

    emit InvestmentAdded(msg.sender, msg.value);
}
```

It almost worked. There are not more run out of gas, but still errors. Bear in mind that, I changed the investors' array to a map.

**Comment by albertocuestacanada** [comment]
Very interesting, I think it is the first time that I've found an `out of gas` for this reason. Well done @obernardovieira.

I think it would be best to just [not use the fallback function](https://programtheblockchain.com/posts/2017/12/16/be-careful-when-using-the-solidity-fallback-function/) and use a normal `payable` function as suggested.

**Pull request merged**
