### PR TITLE
Fix/oz30

### PR DESCRIPTION
**Pull request by albertocuestacanada**
It took me a while to update everything to work with OpenZeppelin contracts 3.0, some tricks they threw in, including changing the ERC20 constructor signature.

I actually had to discard some 20 commits and branch from a branch to try a different approach.

And they broke one of my toys, I had to do some hard stuff to fix `Democracy.sol` :(

### CODE REVIEW

**Comment by albertocuestacanada** [comment]
@obernardovieira, any idea why this fails? It works locally and I updated my packages using `yarn`.

**Comment by obernardovieira** [comment]
The problem is around the erc165 checker, which I do not have much experience, but I've seen a couple of things.
1. in _ERC20Whitelisted_ you are extending _ERC20_ without calling its constructor. Any reason for that?
2. _WhitelistInterfaceId_ might be abstract.
3. in _WhitelistERC165_ you are extending _ERC165_. How _ERC20Whitelisted_ is different from _WhitelistERC165_ and why isn't one extending the other?
4. In _ERC20Whitelisted_'s constructor, how can you call _ERC165Checker._supportsInterface_, since __supportsInterface_ is internal and _ERC165Checker_ is a library? I'm a bit confused.

I had exactly the same problems as the CI and after adding _ERC20_ constructor (from 1.) and removing the "require" in _ERC20Whitelisted_ constructor, it worked (with one exception). I just don't know how you want to fix it.

```
 274 passing
  1 failing

  1) Contract: ERC20Whitelisted
       constructor throws if called with an address not implementing IWhitelist.:
     AssertionError: expected to throw, did not: expected false to be truthy
      at Context.<anonymous> (test/utils.js:14:20)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by albertocuestacanada** [comment]
Next time CI gets different results than my local machine, I should remember to remove the `build` folder and recompile.

Once I got the errors in my machine it was easy to fix. OpenZeppelin just changed the constructor for ERC20 and renamed that function in ERC165Cheker.

**Comment by obernardovieira** [comment]
>  I should remember to remove the build folder and recompile

ahah that usually helps :joy: 
awesome, congrats for this work :clap:

**Pull request merged**
