### PR TITLE
New/access

### PR DESCRIPTION
**Pull request by albertocuestacanada**
I'm refactoring the access contracts according to this discussion I'm having at [OpenZeppelin](https://forum.openzeppelin.com/t/redesigning-access-control-for-the-openzeppelin-contracts/2177).

They still don't see it, but this is very cool stuff. :point_up: 

As a bonus, it uses the EnumerableSet I coded with them, so that all members of a role can be retrieved as an array.

### CODE REVIEW

**Comment by albertocuestacanada** [comment]
So the whole point of this is that there are three layers to code access control in an application.
**Data layer**, coded by Roles.sol. It manages what is a role, what is a membership, and how they should be used so that data integrity is maintained.
**Organization layer**. In this layer we define the conditions for creating roles and membershiprs. We could be coding a `Community` in which there is only one class and any member can add other members. We could be coding a `TwoTiered` organization where there are Users and Admins and Admins have all the power. We could be coding many other different organization, like for example one in which votes are taken for giving roles to accounts. The three contracts provided (`Community`, `TwoTiered` and `Hierarchy`) are both examples and likely to be reused.
**Business layer**. In this layer there is the business logic, which relies on the access control system to restrict actions to authorized actors. There are none of this in `contracts/access`. Maybe I'll create one or two in `contract/examples`. For example `ERC20Mintable` could be reengineered to use `TwoTiered.sol`.

**Comment by albertocuestacanada** [comment]
I coded an example at `contracts/examples/access`.

**Comment by uivlis** [comment]
Hmm, not sure why the CI fails, it runs fine locally, though.

**Comment by albertocuestacanada** [comment]
I think that the CI failed in the last version because I refactored `ERC20Mintable` but kept the name, and somewhere else in the repository the `ERC20Mintable` from OpenZeppelin is used.

Only one `ERC20Mintable` artifact is created at compilation. I try to test mine in `contracts/examples/access/ERC20Mintable.test.ts`, but the artifact picked up is that from the OpenZeppelin version.

**Comment by albertocuestacanada** [comment]
> Currently, the branch coverage for `Hierarchy.sol` and `Roles.sol` is below 90%, but I guess I can skip that since there are a lot of repeating `require`'s.

I'll fix that, thanks for pointing it out.

**Comment by obernardovieira** [comment]
Just edit the PR title, please.

**Comment by albertocuestacanada** [comment]
Thanks!

**Pull request merged**
