### PR TITLE
coverage to one file

### PR DESCRIPTION
**Pull request by obernardovieira**
Running coverage in only one file, the same way we do with tests.

### CODE REVIEW

**Comment by obernardovieira** [comment]
Then ask without approving!

@albertocuestacanada asked this although I was already thinking about it.

if you want to run tests just for whitelist, you can do `yarn test test/access/Whitelist.test.ts` but it didn't work with coverage. With this little change, it's also possible.

`yarn coverage test/access/Whitelist.test.ts`

**Comment by uivlis** [comment]
Okay, what does this do?

**Comment by albertocuestacanada** [comment]
@uivlis, it allows running coverage tests for a single contract. Before to know the test coverage of a particular contract we had to run all the tests in the repo.

@obernardovieira, it only runs the tests for the file specified, so it does what we need. It seems to have some rough edges though.

If I run coverage for a single file:
```alberto@alberto-laptop:~/Code/hq20-contracts$ yarn coverage test/classifieds/Classifieds.test.ts 
```

Then it says it's skipping coverage for a small set of contracts:
```Instrumenting for coverage...
=============================

> access/RBAC.sol
> access/RBACExtended.sol
> access/Whitelist.sol
> classifieds/Classifieds.sol
> examples/energy/EnergyMarket.sol
> examples/introspection/erc165/ERC20Whitelisted.sol
> examples/introspection/erc165/IWhitelist.sol
> examples/introspection/erc165/WhitelistERC165.sol
> examples/introspection/erc165/WhitelistInterfaceId.sol
> exchange/UniswapExchange.sol
> exchange/UniswapFactory.sol
> issuance/Issuance.sol
> lists/DoubleLinkedList.sol
> lists/LinkedList.sol
> lists/mocks/TestLinkedList.sol
> state/StateMachine.sol
> test/classifieds/TestERC721Mintable.sol
> test/examples/introspection/erc165/ERC20WhitelistedMock.sol
> test/exchange/TestUniswapExchange.sol
> test/exchange/TestUniswapFactory.sol
> test/issuance/TestERC20Mintable.sol
> test/state/TestStateMachine.sol
> test/token/TestERC20Dividendable.sol
> token/ERC20Dividendable.sol
> token/IERC20Mintable.sol

Coverage skipped for:
=====================

> drafts/classifieds/ClassifiedsAdvanced.sol
> drafts/issuance/IssuanceAdvanced.sol
> drafts/lists/LinkedListAsArray.sol
> drafts/lists/LinkedListElement.sol
> drafts/lists/LinkedListOOP.sol
> drafts/lists/mocks/OrderedListMock.sol
> drafts/lists/OrderedList.sol
> drafts/lists/TestLinkedListOOP.sol
> drafts/strings/StringConversion.sol
> Migrations.sol
```

Then it runs only the relevant tests (yay!), but I wonder where is it getting the coverage numbers for all those contracts that it didn't test...

```
  Contract: Classifieds
    ✓ openTrade emits an event to signal trade opening (226ms)
    ✓ getTrade can succesfully retrieve a trade (179ms)
    ✓ executeTrade can succesfully close a trade (388ms)
    ✓ executeTrade cannot execute trade when it is not opened (1732ms)
    ✓ cancelTrade can succefully cancel a trade (235ms)
    ✓ cancelTrade cannot cancel a trade by inavlid caller (320ms)
    ✓ cancelTrade cannot cancel a trade which is not Open (329ms)


  7 passing (5s)

-------------------------------------|----------|----------|----------|----------|----------------|
File                                 |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------------------|----------|----------|----------|----------|----------------|
 access/                             |       10 |        0 |     7.14 |     9.52 |                |
  RBAC.sol                           |    19.05 |        0 |    16.67 |    18.18 |... 125,130,131 |
  RBACExtended.sol                   |        0 |        0 |        0 |        0 |... 48,50,63,64 |
  Whitelist.sol                      |        0 |        0 |        0 |        0 |... 49,60,65,66 |
 classifieds/                        |      100 |      100 |      100 |      100 |                |
  Classifieds.sol                    |      100 |      100 |      100 |      100 |                |
 examples/energy/                    |        0 |        0 |        0 |        0 |                |
  EnergyMarket.sol                   |        0 |        0 |        0 |        0 |... ,97,104,111 |
 examples/introspection/erc165/      |        0 |        0 |        0 |        0 |                |
  ERC20Whitelisted.sol               |        0 |        0 |        0 |        0 |... 34,38,44,48 |
  IWhitelist.sol                     |      100 |      100 |      100 |      100 |                |
  WhitelistERC165.sol                |        0 |        0 |        0 |        0 |... 57,68,73,74 |
  WhitelistInterfaceId.sol           |        0 |      100 |        0 |        0 |           9,10 |
 exchange/                           |        0 |        0 |        0 |        0 |                |
  UniswapExchange.sol                |        0 |        0 |        0 |        0 |... 457,458,459 |
  UniswapFactory.sol                 |        0 |        0 |        0 |        0 |... 68,72,78,84 |
 issuance/                           |        0 |        0 |        0 |        0 |                |
  Issuance.sol                       |        0 |        0 |        0 |        0 |... 147,151,152 |
 lists/                              |        0 |        0 |        0 |        0 |                |
  DoubleLinkedList.sol               |        0 |        0 |        0 |        0 |... 204,205,206 |
  LinkedList.sol                     |        0 |        0 |        0 |        0 |... 193,202,203 |
 lists/mocks/                        |        0 |      100 |        0 |        0 |                |
  TestLinkedList.sol                 |        0 |      100 |        0 |        0 |          25,26 |
 state/                              |        0 |        0 |        0 |        0 |                |
  StateMachine.sol                   |        0 |        0 |        0 |        0 |... 92,93,94,97 |
 test/classifieds/                   |      100 |      100 |      100 |      100 |                |
  TestERC721Mintable.sol             |      100 |      100 |      100 |      100 |                |
 test/examples/introspection/erc165/ |        0 |      100 |        0 |        0 |                |
  ERC20WhitelistedMock.sol           |        0 |      100 |        0 |        0 |             21 |
 test/exchange/                      |        0 |        0 |        0 |        0 |                |
  TestUniswapExchange.sol            |        0 |      100 |        0 |        0 |       17,33,50 |
  TestUniswapFactory.sol             |        0 |        0 |        0 |        0 |... 21,22,23,24 |
 test/issuance/                      |      100 |      100 |      100 |      100 |                |
  TestERC20Mintable.sol              |      100 |      100 |      100 |      100 |                |
 test/state/                         |        0 |      100 |        0 |        0 |                |
  TestStateMachine.sol               |        0 |      100 |        0 |        0 |        9,16,20 |
 test/token/                         |      100 |      100 |      100 |      100 |                |
  TestERC20Dividendable.sol          |      100 |      100 |      100 |      100 |                |
 token/                              |        0 |        0 |        0 |        0 |                |
  ERC20Dividendable.sol              |        0 |        0 |        0 |        0 |... 41,42,50,52 |
  IERC20Mintable.sol                 |      100 |      100 |      100 |      100 |                |
-------------------------------------|----------|----------|----------|----------|----------------|
All files                            |     6.33 |     3.61 |     5.41 |      6.3 |                |
-------------------------------------|----------|----------|----------|----------|----------------|

> Istanbul reports written to ./coverage/ and ./coverage.json
> solidity-coverage cleaning up, shutting down ganache server
Done in 33.53s.
```

**Comment by obernardovieira** [comment]
So, I see coverage for 
RBAC.sol
Classifieds.sol
IWhitelist.sol
TestERC721Mintable.sol
TestERC20Mintable.sol
TestERC20Dividendable.sol
IERC20Mintable.sol

When you run coverage for Classifieds, you are calling
Classifieds.sol
TestERC721Mintable.sol
TestERC20Mintable.sol

You also see RBAC.sol because there's a migration file (I didn't know this, I've just removed and the coverage dropped to zero)

What is missing?
IWhitelist.sol
TestERC20Dividendable.sol
IERC20Mintable.sol

What do these files have in common? Empty contracts or all empty methods. Therefore 100% coverage on them. It's right. If there's no line that the coverage tool can count, then there's no missing line to count and if there's no missing line, the coverage is zero.

**Comment by albertocuestacanada** [comment]
@obernardovieira, I see. That is a very good explanation.

It doesn't make much sense running coverage on interfaces, does it? Can we exclude them somehow? Maybe just ignoring I*.sol files?

Regarding empty contracts, I think that TestERC20Dividendable.sol might change soon and stop messing up the coverage report.

**Comment by obernardovieira** [comment]
It doesn't, because there's nothing to cover.
I couldn't ignore like that, so I've put the complete path. Still, there are 3 empty files. Wait for CI, have a look and feel free to merge.

**Comment by albertocuestacanada** [comment]
Happy to use it as is. @uivlis, please review and merge.

And with review, I mean check this branch out locally and test the feature. Please ask questions if you have any.

**Comment by uivlis** [comment]
Hmm, for me, this command fails if not called with `sudo` prepended. Is it supposed to, or is this even an issue?

**Comment by obernardovieira** [comment]
The coverage command runs the test.sh script with SOLIDITY_COVERAGE flag as true. Can you identify which step requires the sudo? It should not require it.

**Comment by uivlis** [comment]
Well, all I get is:
```
Error: Istanbul coverage reports could not be generated. 
EACCES: permission denied, open '.........(path to report here)'
```

**Comment by uivlis** [comment]
But, on the other side, that happens also when I run `yarn coverage` with no file.

**Comment by obernardovieira** [comment]
`yarn coverage` fails if you have ganache open, because "[Coverage launches its own in-process ganache server](https://github.com/sc-forks/solidity-coverage#usage-notes)".

Looks like you have your file system permissions a bit messed up. Or maybe the npm or yarn. There is something wrong with your file system permissions.

It should not require `sudo`. CI runs smoothly, as you can see, without any sudo.

Check your file system permissions with `ls -la`, try to create files with `touch someemptyfile.txt` and check who you are in a given session on the command line with `whoami`. If you do have problems,  ask me on slack :+1:

You should never, ever be required sudo when using npm or yarn scripts, whatever that script is.

**Pull request merged**
