### PR TITLE
Feature/strings trim

### PR DESCRIPTION
**Pull request by albertocuestacanada**
Just breaking down one function

### CODE REVIEW

**Comment by obernardovieira** [comment]
just don't merge PR branches into PR branches, please. I can get a hell of a mess.
Always update (rebase) from the parent branch.

**Comment by albertocuestacanada** [comment]
I think it is ready for merging now.

What do I do when I work on a PR branch that needs features that haven't been merged into dev yet? Wait patiently?

**Comment by albertocuestacanada** [comment]
image.

Weird, tests pass for me.

**Comment by albertocuestacanada** [comment]
Tests should pass now. I've moved it to drafts since we might not even ever use it.

**Pull request merged**
